FROM golang:1.13-alpine3.10 AS builder

ENV GOPROXY=https://goproxy.cn,direct
ENV GO111MODULE="on"
ENV ENV="develop"

WORKDIR /app

COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download


COPY . .

RUN go build -o main /app/main.go

FROM alpine:latest

COPY --from=builder /app/main .

EXPOSE 4000

ENTRYPOINT  ["./main"]